### ISSUE TITLE
alpha testnet checklist

### ISSUE THREAD

**Issue by soc1c** [dothereum/dothereum#18]
- [x] open source repository https://github.com/dothereum/dothereum/
- [x] proper bootnode `/ip4/51.15.116.226/tcp/34242/p2p/QmTwkE6jMezw3JdrMKTBqT7RKMn2XuKnSnYWHWM7Y3pSKJ`
- [x] network should finalize blocks, ref #17
