### ISSUE TITLE
beta testnet checklist

### ISSUE THREAD

**Issue by soc1c** [dothereum/dothereum#22]
0.2 "beta" to enable users executing arbitrary contracts

- [x] basic contracts runtime, ref #9 
- [x] sensible genesis alloc, ref #21
- [x] bundle chain-spec for convenience, ref #8

**Comment by soc1c** [comment]
beta will be gamma
